Increase build stability, ensure that we only push net source changes, even with sha injection.

diff --git a/docker/build_image b/docker/build_image
--- a/docker/build_image
+++ b/docker/build_image
@@ -133,7 +133,7 @@ done < <(cat $Dockerfile | grep FROM | xargs -n2 echo | cut -d ' ' -f2)
 
 cat $0 | addToDigest
 
-mounts="-v /var/run/docker.sock:/var/run/docker.sock:ro"
+mounts="-v /var/run/docker.sock:/var/run/docker.sock:ro -v /tmp/last.build:/build/last.build"
 #- The dockerfile's parent directory is mount as 'src' into the build process.
 mounts="$mounts --mount type=bind,source=$(realpath $(dirname $Dockerfile)),target=/build/src"
 recursiveDigest "$(dirname $Dockerfile)" | addToDigest
@@ -176,32 +176,51 @@ done
 #- filtering.
 # Add in the built-from-sha here, too.
 
-$DIR/find-parent-pr-merge.sh > $DIR/built-from-sha
+builtFromSha="$($DIR/find-parent-pr-merge.sh)"
 
 BUILD_CMD="
+set -x
 cat src/.dockerignore /assist/.dockerignore | grep -v '#' | awk '{print \"src/\"\$0}' > .dockerignore ; \\
-cp src/$(basename $Dockerfile) /tmp/Dockerfile"
+cp src/$(basename $Dockerfile) /tmp/Dockerfile && \\
+echo 'COPY last.build/version /built-from-sha' >> /tmp/Dockerfile"
 
-# TODO -- I want to find a clever way to only run certain build steps iff the previous run steps were not previously
-# cached.  For now, these build steps cause too much noise in edge-apache and are not necessary.
-if [[ "$baseTag" != "edge-apache" ]]; then
-  BUILD_CMD="${BUILD_CMD} && \\
-  cp /assist/built-from-sha ./ && \\
-  cp /assist/deploy.sh ./ && \\
-  cp /assist/post-to-slack.sh ./ && \\
-  chmod +x ./post-to-slack.sh && \\
-  echo 'COPY built-from-sha /built-from-sha' >> /tmp/Dockerfile && \\
-  echo 'COPY deploy.sh /bin/deploy' >> /tmp/Dockerfile && \\
-  echo 'COPY post-to-slack.sh /bin/post-to-slack' >> /tmp/Dockerfile"
+if ! rm -rf /tmp/last.build/; then
+  echo "Could not clean /tmp/last.build/, required for build to continue"
+  echo "Perhaps permissions issue in this directory?"
+  exit 1
 fi
 
-BUILD_CMD="${BUILD_CMD} && \\
-docker build --rm --force-rm \\
-  --tag $baseTag --cache-from $tag $* -f /tmp/Dockerfile ."
+mkdir -p /tmp/last.build
+if imageExists; then
+  docker image inspect "$tag" | grep "\"Id\":" | sed -e 's/\s*//' | cut -d'"' -f4 > /tmp/last.build/id
+  docker image inspect "$tag" | grep "\"edu.ucsf.mountetna.version\":" | sed -e 's/\s*//' | tail -n 1 | cut -d'"' -f4 > /tmp/last.build/version
+fi
 
+DOCKER_BUILD_CMD="docker build --rm --force-rm \\
+  --iidfile=/build/next.build/id \\
+  --label=edu.ucsf.mountetna.version=\$(cat /build/last.build/version) \\
+  --tag $baseTag \\
+  --cache-from etnaagent/$baseTag:staging \\
+  --cache-from $tag \\
+  --cache-from $baseTag \\
+  $* -f /tmp/Dockerfile ."
+
+BUILD_CMD="${BUILD_CMD} && \\
+mkdir -p /build/next.build/ && \\
+mkdir -p /build/last.build/ && \\
+touch /build/last.build/id && \\
+touch /build/last.build/version && \\
+$DOCKER_BUILD_CMD"
+
+#- For images that are intended to be tagged and pushed to a repository, we'll want to rebuild in the correct version
+#- labeling for this given commit, assuming that the built sha is differing.
 if [[ "$baseTag" != "$tag" ]]; then
   BUILD_CMD="$BUILD_CMD && \\
-docker tag $baseTag $tag"
+if [[ \"\$(cat /build/last.build/id)\" != \"\$(cat /build/next.build/id)\" ]]; then \\
+  echo '${builtFromSha}' > /build/last.build/version
+  $DOCKER_BUILD_CMD
+  docker tag $baseTag $tag
+fi"
 fi
 
 echo "$BUILD_CMD" | addToDigest
@@ -231,5 +250,8 @@ set -x
 # Docker can 'leak' intermediate build images from different runs, unfortunately, even with --rm and --force-rm.
 # This will atleast prune between runs to keep it minimal
 [[ -z "$IS_CI" ]] && docker image prune -f
+
+# Build the base layer.
 docker run --rm -w /build -v "${DIR}:/assist:ro" $mounts docker:19.03.12 sh -c "$BUILD_CMD"
+
 touch $marker
